# Generated by Django 5.0.1 on 2024-01-28 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidadeType', models.CharField(max_length=250)),
                ('completeName', models.CharField(max_length=200)),
                ('documentType', models.CharField(max_length=350)),
                ('documentNumber', models.CharField(max_length=350)),
            ],
        ),
    ]
